### ISSUE TITLE
S2: Ashwood Copse (Design directions)

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/Legend_of_Wesmere_Revised#15]
```
### S2 - Ashwood Copse

After a few weeks of patrol, Landar and Kalenz are meant to return to the Ka'lian keep for orders. However, they come across a village on the border that is suspiciously empty, though there are suspiciously many ashes scattered around. Landar makes the decision to disobey the Ka'lian's orders and investigate, since he chooses to prioritize the lives of his kin. Upon investigating the village, they unwittingly trip some explosives, setting the entire village ablaze. Orcish archers and goblins emerge from the surrounding forest. They belong to the Embershard clan (which predictably specializes in the use of fire). They fight off the orcs and question them. It turns out that the elves were originally captured by the Embershard clan, but the rival Blackcrest clan then ambushed them and took the elves as their own hostages to be a bargaining chip. Landar again makes a decision to pursue the orcs despite receiving another order to return to the Ka'lian.

- Recruits: Archer, Fighter, Civilian
- Civilian discovered once Landar enters the village
```

I see this scenario partially done. 
@nemaara 

What are next things to do here?

> Civilian discovered once Landar enters the village

which village? and does it specifically have to be Landar?

> Upon investigating the village, they unwittingly trip some explosives, setting the entire village ablaze

Do we burn every village to rubble with animation? (it's what I understood)

> Orcish archers and goblins emerge from the surrounding forest

All of them get the 'embershard' ability?
Count is 10/12/14?
And I suppose one of them is supposed be a hero/elite among them which when killed reveals the the info mentioned in the draft?

cc @AnekronCZ

**Comment by knyghtmare** [comment]
Update: 

So, I think I did most of the heavy code in Ashwood Copse. Just some dialogue and flavor events left. The scenario is medium in difficulty so I guess it's fine.

**Comment by nemaara** [comment]
> > Civilian discovered once Landar enters the village
> 
> which village? and does it specifically have to be Landar?
Village as in the village in general, perhaps once you move to a certain hex. It doesn't have to be Landar.

> > Upon investigating the village, they unwittingly trip some explosives, setting the entire village ablaze
> 
> Do we burn every village to rubble with animation? (it's what I understood)
Up to your interpretation.

> > Orcish archers and goblins emerge from the surrounding forest
> 
> All of them get the 'embershard' ability? Count is 10/12/14? And I suppose one of them is supposed be a hero/elite among them which when killed reveals the the info mentioned in the draft?
You understood correctly to both. All embershard units have the embershard ability, and count of units is however many makes the scenario tricky. There should also be some amount of heroes/elites which could vary on difficulty.

**Comment by nemaara** [comment]
Okay I played the scenario really quickly and have some comments. I can handle this TODO list later as well.

1. Overall gameplay is good. 
2. I think there's too many units, both in terms of your gold and also in terms of enemies. This may be better as a very fast scenario with not a lot of exp.
3. Exploding village could also cause some damage to the surrounding forest and terrain.
4. What if we had the scenario entirely at night?

**Comment by knyghtmare** [comment]
> I think there's too many units, both in terms of your gold and also in terms of enemies. This may be better as a very fast scenario with not a lot of exp.

Can tone down unit counts, and can also limit player's army to. Will auto-recall a set number and remove castes linked with keep to block recalling/recruiting.

> Exploding village could also cause some damage to the surrounding forest and terrain.

Can do this tomorrow

> What if we had the scenario entirely at night?

Sounds delightful. Should be done.

**Comment by knyghtmare** [comment]
The scenario is mostly done, with the added SFX code now. I am closing it now, but a new issue can be opened if further refinements are required. I also think the enemy strength can be toned down further.
